version: "3.8"

services:
  actix-react-oidc-keycloakdb:
    container_name: actix-react-oidc-keycloakdb
    image: postgres:12.9
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    ports:
      - 52632:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h actix-react-oidc-keycloakdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - actix-react-oidc-network

  actix-react-oidc-keycloak:
    container_name: actix-react-oidc-keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://actix-react-oidc-keycloakdb:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: PdZoV9NpYuq#zdsYXfHo
      KC_FEATURES:
        token-exchange
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_HTTP_ENABLED: 'true'
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_CACHE_STACK: tcp
      KC_HEALTH_ENABLED: 'true'
    volumes:
      - ./.keycloak:/opt/keycloak/data/import/:ro
    command:
      - "start"
      - "--http-port 8080"
      - "--proxy=passthrough"
      - "--import-realm"
    ports:
      - 52633:8080
    depends_on:
      - actix-react-oidc-keycloakdb
    networks:
      - actix-react-oidc-network

  actix-react-oidc-backend:
    container_name: actix-react-oidc-backend
    image: actix-react-oidc-backend
    build: ./src/backend
    deploy:
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthcheck" ]
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      AUTHORITY: http://actix-react-oidc-keycloak:8080/realms/react-example
    depends_on:
      - actix-react-oidc-keycloak
    ports:
      - "52634:8080"
    networks:
      - actix-react-oidc-network

  actix-react-oidc-web:
    container_name: actix-react-oidc-web
    image: actix-react-oidc-web
    build: 
      context: ./src/react
      args:
        REACT_APP_KEYCLOAK_CLIENT_ID: react
        REACT_APP_KEYCLOAK_URL: http://localhost:52633/realms/react-example
        REACT_APP_BACKEND_URL: http://localhost:52634
    deploy:
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "52635:3000"
    depends_on:
      - actix-react-oidc-keycloak
    networks:
      - actix-react-oidc-network

networks:
  actix-react-oidc-network:
    name: actix-react-oidc-network
    driver: bridge

volumes:
  keycloakdb:
    driver: local